---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: quarkuscoffeeshop-cicd
  generateName: quarkuscoffeeshop-majestic-monolith-
  labels:
    app: quarkuscoffeeshop-majestic-monolith
    argocd.argoproj.io/instance: quarkuscoffeeshop-cicd
    tekton.dev/pipeline: build-and-push-quarkuscoffeeshop-majestic-monolith
spec:
  pipelineRef:
    name: build-and-push-quarkuscoffeeshop-majestic-monolith
  resources:
    - name: app-git
      resourceRef:
        name: quarkuscoffeeshop-majestic-monolith-git
    - name: image
      resourceRef:
        name: quarkuscoffeeshop-majestic-monolith-image
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: quarkuscoffeeshop-majestic-monolith-shared-workspace-pvc
    - name: maven-settings
      persistentVolumeClaim:
        claimName: quarkuscoffeeshop-majestic-monolith-maven-settings-pvc
