apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-quarkuscoffeeshop-web
  labels:
    app: quarkuscoffeeshop-web
spec:
  params:
    - default: {{ coalesce .Values.global.quarkuscoffeeshopWeb.imageTag "latest" }}
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
    - default: {{ include "quarkuscoffeeshop-pipelines.imageRegistryHostname" . }}/{{ .Values.global.imageregistry.account }}/quarkuscoffeeshop-web
      name: quay-io-repository
      type: string
    - default: latest
      name: quay-io-image-tag-name
      type: string
    - default: {{ .Values.global.quarkuscoffeeshopWeb.revision | quote }}
      name: revision
      type: string
{{ if .Values.enableWebhookSecret }}
    - default: webhook-secret
      description: Webhook secret name
      name: webhook-secret
      type: string
{{ end }}
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://{{ .Values.global.git.hostname }}/{{ .Values.global.git.account }}/quarkuscoffeeshop-web'
        - name: revision
          value: $(params.revision)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-run
      params:
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - '-DskipTests'
            - clean
            - package
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: build-java-app-image
      params:
        - name: CONTEXT
          value: .
        - name: DOCKERFILE
          value: src/main/docker/Dockerfile.jvm
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-web:$(params.IMAGE_TAG)
        - name: TLSVERIFY
          value: 'false'
      runAfter:
        - maven-run
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: tag-test-image
      params:
        - name: SCRIPT
          value: |
            oc tag quarkuscoffeeshop-web:$(params.IMAGE_TAG) quarkuscoffeeshop-web:latest
      runAfter:
        - build-java-app-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: push-quarkuscoffeeshop-web-image-to-quay
      params:
        - name: srcImageURL
          value: "docker://image-registry.openshift-image-registry.svc:5000/quarkuscoffeeshop-cicd/quarkuscoffeeshop-web:$(params.IMAGE_TAG)"
        - name: destImageURL
          value: "docker://{{ include "quarkuscoffeeshop-pipelines.imageRegistryHostname" . }}/{{ .Values.global.imageregistry.account }}/quarkuscoffeeshop-web:$(params.IMAGE_TAG)"
      runAfter:
        - tag-test-image
      taskRef:
        kind: Task
        name: skopeo-copy
    - name: push-to-test-env
      params:
        - name: SCRIPT
          value: |
            oc rollout restart -n quarkuscoffeeshop-demo deployment quarkuscoffeeshop-web || /bin/true
      runAfter:
        - push-quarkuscoffeeshop-web-image-to-quay
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: shared-workspace
    - name: maven-settings
