---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: quay-auth-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: quay-auth-secret
    template:
      metadata:
        annotations:
          # Tekton magic, see https://tekton.dev/vault/pipelines-v0.15.2/auth/
          tekton.dev/docker-0: https://{{ include "quarkuscoffeeshop-pipelines.imageRegistryHostname" . }}
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: {{ .Values.imageregistrysecret.key }}
