{{- if .Values.mirrorMaker.enabled }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker
metadata:
  name: store-to-homeoffice-mm
spec:
  consumer:
    bootstrapServers: >-
      {{ .Values.mirrorMaker.localKafkaBootstrapHost }}:{{ .Values.mirrorMaker.localKafkaBootstrapPort }}
    groupId: my-source-group-id
  include: .*
  livenessProbe:
    failureThreshold: 2
    initialDelaySeconds: 1
    periodSeconds: 1
    successThreshold: 1
    timeoutSeconds: 2
  producer:
    bootstrapServers: >-
      {{ .Values.mirrorMaker.remoteKafkaBootstrapHost }}.{{ .Values.global.hubClusterDomain }}:443
    tls:
      trustedCertificates:
        - certificate: ca.crt
          secretName: {{ .Values.mirrorMaker.certSecretName }}
  readinessProbe:
    failureThreshold: 2
    initialDelaySeconds: 0
    periodSeconds: 1
    successThreshold: 2
    timeoutSeconds: 2
  replicas: 1
  version: 3.1.0
{{- end }}
